### ISSUE TITLE
Mobil fejlesztési nyelv

### ISSUE THREAD

**Issue by zlaval** [arphox/tudasbazis#8]
Jelenleg Java van fő ajánlott nyelvként, valamint Swift IOS-re.
Egy Kotlint érdemes lenne megemlíteni, ha már az a fő nyelv androidon.

**Comment by arphox** [comment]
Köszönöm! Több téren nem vagyok annyira tájékozódott. Gondoltam a Kotlin-ra, csak nem sokat tudok róla így nem mertem beleírni, nem tudom mennyire kezdő-barát. Kiegészítem.

De ezt a megfelelő PR (#6) alá kellett volna; ezt az issue-t zárom, és belinkelem a PR-be. :-)

**Comment by zlaval** [comment]
Nincsmit. Nem nehezebb a Javanál, viszont sokkal kultúráltabb. Ezért is támodatja Google.
